<html>
<head>
<style type="text/css">
#tables
  {
  font-family:"Trebuchet MS", Arial, Helvetica, sans-serif;
  width:100%;
  border-collapse:collapse;
  }

#tables td, #tables th 
  {
  font-size:1em;
  border:1px solid #98bf21;
  padding:3px 7px 2px 7px;
  }

#tables th 
  {
  font-size:1.1em;
  text-align:left;
  padding-top:5px;
  padding-bottom:4px;
  background-color:#A7C942;
  color:#ffffff;
  }

#tables tr.alt td 
  {
  color:#000000;
  background-color:#EAF2D3;
  }
</style>
</head>
<body>
<table id="tables">
<tr>
<th>No</th>
<th>field1</th>
<th>field2</th>
<th>field3</th>
<th>field4</th>
<th>field5</th>
</tr>
    <tr>
<td>  1  </td>
<td>  2013-10-18 06:12:26,243  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.sysman.ias.ias.IASIntegration  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  2  </td>
<td>  2013-10-18 06:12:26,666  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.sysman.eml.target.slb.common.SLBIntegration  </td>
<td>    </td>
</tr>
    <tr>
<td>  3  </td>
<td>  2013-10-18 06:12:26,805  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.sysman.eml.ssl.intg.SSLIntegration  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  4  </td>
<td>  2013-10-18 06:12:26,964  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.tip.oem.central.domain.ProcessConnectDomainIntg  </td>
<td>    </td>
</tr>
    <tr>
<td>  5  </td>
<td>  2013-10-18 06:12:26,965  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.tip.oem.central.instance.ProcessConnectInstanceIntg  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  6  </td>
<td>  2013-10-18 06:12:26,968  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.webdb.admin.em.PortalIntegration  </td>
<td>    </td>
</tr>
    <tr>
<td>  7  </td>
<td>  2013-10-18 06:12:26,969  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.webdb.admin.em.SSOIntegration  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  8  </td>
<td>  2013-10-18 06:12:26,970  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.reports.em.RepIntg  </td>
<td>    </td>
</tr>
    <tr>
<td>  9  </td>
<td>  2013-10-18 06:12:26,971  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.sysman.ocs.mntr.target.OcsEmailIntegration  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  10  </td>
<td>  2013-10-18 06:12:26,976  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.sysman.ocs.mntr.target.OcsOidIntegration  </td>
<td>    </td>
</tr>
    <tr>
<td>  11  </td>
<td>  2013-10-18 06:12:26,977  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.sysman.ocs.mntr.target.OcsOvfIntegration  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  12  </td>
<td>  2013-10-18 06:12:26,978  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.sysman.ocs.mntr.target.OcsWebconfIntegration  </td>
<td>    </td>
</tr>
    <tr>
<td>  13  </td>
<td>  2013-10-18 06:12:26,979  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.sysman.ocs.mntr.target.OcsWirelessIntg  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  14  </td>
<td>  2013-10-18 06:12:26,980  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.sysman.ocs.mntr.target.OcsCalGrpIntegration  </td>
<td>    </td>
</tr>
    <tr>
<td>  15  </td>
<td>  2013-11-07 01:52:13,361  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.sysman.ias.ias.IASIntegration  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  16  </td>
<td>  2013-11-07 01:52:13,735  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.sysman.eml.target.slb.common.SLBIntegration  </td>
<td>    </td>
</tr>
    <tr>
<td>  17  </td>
<td>  2013-11-07 01:52:13,891  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.sysman.eml.ssl.intg.SSLIntegration  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  18  </td>
<td>  2013-11-07 01:52:14,031  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.tip.oem.central.domain.ProcessConnectDomainIntg  </td>
<td>    </td>
</tr>
    <tr>
<td>  19  </td>
<td>  2013-11-07 01:52:14,031  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.tip.oem.central.instance.ProcessConnectInstanceIntg  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  20  </td>
<td>  2013-11-07 01:52:14,031  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.webdb.admin.em.PortalIntegration  </td>
<td>    </td>
</tr>
    <tr>
<td>  21  </td>
<td>  2013-11-07 01:52:14,031  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.webdb.admin.em.SSOIntegration  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  22  </td>
<td>  2013-11-07 01:52:14,031  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.reports.em.RepIntg  </td>
<td>    </td>
</tr>
    <tr>
<td>  23  </td>
<td>  2013-11-07 01:52:14,031  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.sysman.ocs.mntr.target.OcsEmailIntegration  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  24  </td>
<td>  2013-11-07 01:52:14,031  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.sysman.ocs.mntr.target.OcsOidIntegration  </td>
<td>    </td>
</tr>
    <tr>
<td>  25  </td>
<td>  2013-11-07 01:52:14,031  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.sysman.ocs.mntr.target.OcsOvfIntegration  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  26  </td>
<td>  2013-11-07 01:52:14,063  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.sysman.ocs.mntr.target.OcsWebconfIntegration  </td>
<td>    </td>
</tr>
    <tr>
<td>  27  </td>
<td>  2013-11-07 01:52:14,063  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.sysman.ocs.mntr.target.OcsWirelessIntg  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  28  </td>
<td>  2013-11-07 01:52:14,063  </td>
<td>  Orion Launcher  </td>
<td>  ERROR  </td>
<td>  app.ContextInitializer contextInitialized.271 - Integration Class not found: oracle.sysman.ocs.mntr.target.OcsCalGrpIntegration  </td>
<td>    </td>
</tr>
    <tr>
<td>  29  </td>
<td>  2013-11-07 02:56:26,407  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.303 - Got a fatal exeption when getting a connection; Error code = 17002; Cleaning up cache and retrying  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  30  </td>
<td>  2013-11-07 02:56:26,423  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.306 - Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:296)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getPrivateConnection(ConnectionService.java:605)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getRepositoryVersionAndMode(ConnectionService.java:368)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.verifyRepositoryEx(ConnectionService.java:395)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.verifyRepository(ConnectionService.java:450)
	at oracle.sysman.emdrep.jobs.Dispatcher.mainTask(Dispatcher.java:1952)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.run(OmsServiceDriver.java:164)
  </td>
</tr>
    <tr>
<td>  31  </td>
<td>  2013-11-07 02:56:26,423  </td>
<td>  OmsServiceDriver thread  </td>
<td>  ERROR  </td>
<td>  conn.ConnectionService verifyRepositoryEx.433 - Invalid Connection Pool. ERROR = Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  32  </td>
<td>  2013-11-07 02:56:26,423  </td>
<td>  OmsServiceDriver thread  </td>
<td>  ERROR  </td>
<td>  em.jobs mainTask.1956 - encountered error:   </td>
<td>  java.sql.SQLException: Io “Ï≥£: Connection reset by peer: socket write error
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:972)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1252)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3290)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3395)
	at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4222)
	at oracle.sysman.util.jdbc.PreparedStatementWrapper.execute(PreparedStatementWrapper.java:630)
	at oracle.sysman.emdrep.jobs.Dispatcher.getSteps(Dispatcher.java:1585)
	at oracle.sysman.emdrep.jobs.Dispatcher.process(Dispatcher.java:1203)
	at oracle.sysman.emdrep.jobs.Dispatcher.mainTask(Dispatcher.java:1912)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.run(OmsServiceDriver.java:164)
  </td>
</tr>
    <tr>
<td>  33  </td>
<td>  2013-11-07 02:56:31,430  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.303 - Got a fatal exeption when getting a connection; Error code = 17002; Cleaning up cache and retrying  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  34  </td>
<td>  2013-11-07 02:56:31,430  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.306 - Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:296)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getSystemConnection(ConnectionService.java:683)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.getConnection(OmsServiceDriver.java:88)
	at oracle.sysman.emdrep.jobs.Dispatcher.getConnection(Dispatcher.java:1054)
	at oracle.sysman.emdrep.jobs.Dispatcher.process(Dispatcher.java:1200)
	at oracle.sysman.emdrep.jobs.Dispatcher.mainTask(Dispatcher.java:1912)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.run(OmsServiceDriver.java:164)
  </td>
</tr>
    <tr>
<td>  35  </td>
<td>  2013-11-07 02:56:31,430  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.303 - Got a fatal exeption when getting a connection; Error code = 17002; Cleaning up cache and retrying  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  36  </td>
<td>  2013-11-07 02:56:31,430  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.306 - Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:296)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getPrivateConnection(ConnectionService.java:605)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getRepositoryVersionAndMode(ConnectionService.java:368)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.verifyRepositoryEx(ConnectionService.java:395)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.verifyRepository(ConnectionService.java:450)
	at oracle.sysman.emdrep.jobs.Dispatcher.mainTask(Dispatcher.java:1952)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.run(OmsServiceDriver.java:164)
  </td>
</tr>
    <tr>
<td>  37  </td>
<td>  2013-11-07 02:56:31,446  </td>
<td>  OmsServiceDriver thread  </td>
<td>  ERROR  </td>
<td>  conn.ConnectionService verifyRepositoryEx.433 - Invalid Connection Pool. ERROR = Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  38  </td>
<td>  2013-11-07 02:56:56,578  </td>
<td>  NotificationMgrThread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.303 - Got a fatal exeption when getting a connection; Error code = 17002; Cleaning up cache and retrying  </td>
<td>    </td>
</tr>
    <tr>
<td>  39  </td>
<td>  2013-11-07 02:56:56,578  </td>
<td>  NotificationMgrThread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.306 - Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:296)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getSystemConnection(ConnectionService.java:683)
	at oracle.sysman.emdrep.notification.NotificationMgr.getConnection(NotificationMgr.java:252)
	at oracle.sysman.emdrep.notification.NotificationMgr.resetConnection(NotificationMgr.java:298)
	at oracle.sysman.emdrep.notification.NotificationMgr.run(NotificationMgr.java:1190)
  </td>
</tr>
    <tr class="alt">
<td>  40  </td>
<td>  2013-11-07 02:56:57,482  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.303 - Got a fatal exeption when getting a connection; Error code = 17002; Cleaning up cache and retrying  </td>
<td>    </td>
</tr>
    <tr>
<td>  41  </td>
<td>  2013-11-07 02:56:57,482  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.306 - Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:296)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getSystemConnection(ConnectionService.java:683)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.getConnection(OmsServiceDriver.java:88)
	at oracle.sysman.emdrep.jobs.Dispatcher.getConnection(Dispatcher.java:1054)
	at oracle.sysman.emdrep.jobs.Dispatcher.process(Dispatcher.java:1200)
	at oracle.sysman.emdrep.jobs.Dispatcher.mainTask(Dispatcher.java:1912)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.run(OmsServiceDriver.java:164)
  </td>
</tr>
    <tr class="alt">
<td>  42  </td>
<td>  2013-11-07 02:57:20,789  </td>
<td>  XMLLoader0  </td>
<td>  ERROR  </td>
<td>  emdrep.XMLLoaderContext logLoaderParameters.2179 - πÿ±’µƒ¡¨Ω”  </td>
<td>  java.sql.SQLException: πÿ±’µƒ¡¨Ω”
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:207)
	at oracle.jdbc.driver.PhysicalConnection.createStatement(PhysicalConnection.java:912)
	at oracle.jdbc.driver.PhysicalConnection.createStatement(PhysicalConnection.java:888)
	at oracle.jdbc.driver.PhysicalConnection.initUserName(PhysicalConnection.java:3108)
	at oracle.jdbc.driver.PhysicalConnection.getUserName(PhysicalConnection.java:3128)
	at oracle.jdbc.OracleConnectionWrapper.getUserName(OracleConnectionWrapper.java:321)
	at oracle.sysman.util.jdbc.ConnectionWrapper.getUserName(ConnectionWrapper.java:1143)
	at oracle.sql.SQLName.init(SQLName.java:141)
	at oracle.sql.SQLName.<init>(SQLName.java:89)
	at oracle.sql.ArrayDescriptor.createDescriptor(ArrayDescriptor.java:148)
	at oracle.sql.ArrayDescriptor.createDescriptor(ArrayDescriptor.java:114)
	at oracle.sysman.emdrep.dbjava.loader.XMLLoaderContext.logLoaderParameters(XMLLoaderContext.java:2157)
	at oracle.sysman.emdrep.dbjava.loader.XMLLoaderContext.keepAlive(XMLLoaderContext.java:572)
	at oracle.sysman.emdrep.dbjava.loader.XMLLoader.run(XMLLoader.java:1140)
	at java.lang.Thread.run(Thread.java:534)
  </td>
</tr>
    <tr>
<td>  43  </td>
<td>  2013-11-07 02:57:39,525  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.303 - Got a fatal exeption when getting a connection; Error code = 17002; Cleaning up cache and retrying  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  44  </td>
<td>  2013-11-07 02:57:39,525  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.306 - Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:296)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getPrivateConnection(ConnectionService.java:605)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getRepositoryVersionAndMode(ConnectionService.java:368)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.verifyRepositoryEx(ConnectionService.java:395)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.verifyRepository(ConnectionService.java:450)
	at oracle.sysman.emdrep.jobs.Dispatcher.mainTask(Dispatcher.java:1952)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.run(OmsServiceDriver.java:164)
  </td>
</tr>
    <tr>
<td>  45  </td>
<td>  2013-11-07 02:57:43,627  </td>
<td>  NotificationMgrThread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.303 - Got a fatal exeption when getting a connection; Error code = 17002; Cleaning up cache and retrying  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  46  </td>
<td>  2013-11-07 02:57:43,627  </td>
<td>  NotificationMgrThread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.306 - Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:296)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getSystemConnection(ConnectionService.java:683)
	at oracle.sysman.emdrep.notification.NotificationMgr.getConnection(NotificationMgr.java:252)
	at oracle.sysman.emdrep.notification.NotificationMgr.resetConnection(NotificationMgr.java:298)
	at oracle.sysman.emdrep.notification.NotificationMgr.run(NotificationMgr.java:1190)
  </td>
</tr>
    <tr>
<td>  47  </td>
<td>  2013-11-07 02:58:00,553  </td>
<td>  OmsServiceDriver thread  </td>
<td>  ERROR  </td>
<td>  conn.ConnectionService verifyRepositoryEx.433 - Invalid Connection Pool. ERROR = Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  48  </td>
<td>  2013-11-07 02:58:26,605  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.303 - Got a fatal exeption when getting a connection; Error code = 17002; Cleaning up cache and retrying  </td>
<td>    </td>
</tr>
    <tr>
<td>  49  </td>
<td>  2013-11-07 02:58:26,605  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.306 - Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:296)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getSystemConnection(ConnectionService.java:683)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.getConnection(OmsServiceDriver.java:88)
	at oracle.sysman.emdrep.failover.OMSHeartbeatRecorder.getConnection(OMSHeartbeatRecorder.java:104)
	at oracle.sysman.emdrep.failover.OMSHeartbeatRecorder.heartbeat(OMSHeartbeatRecorder.java:239)
	at oracle.sysman.emdrep.failover.OMSHeartbeatRecorder.mainTask(OMSHeartbeatRecorder.java:427)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.run(OmsServiceDriver.java:164)
  </td>
</tr>
    <tr class="alt">
<td>  50  </td>
<td>  2013-11-07 02:58:30,646  </td>
<td>  NotificationMgrThread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.303 - Got a fatal exeption when getting a connection; Error code = 17002; Cleaning up cache and retrying  </td>
<td>    </td>
</tr>
    <tr>
<td>  51  </td>
<td>  2013-11-07 02:58:30,646  </td>
<td>  NotificationMgrThread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.306 - Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:296)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getSystemConnection(ConnectionService.java:683)
	at oracle.sysman.emdrep.notification.NotificationMgr.getConnection(NotificationMgr.java:252)
	at oracle.sysman.emdrep.notification.NotificationMgr.resetConnection(NotificationMgr.java:298)
	at oracle.sysman.emdrep.notification.NotificationMgr.run(NotificationMgr.java:1190)
  </td>
</tr>
    <tr class="alt">
<td>  52  </td>
<td>  2013-11-07 02:58:47,634  </td>
<td>  OmsServiceDriver thread  </td>
<td>  ERROR  </td>
<td>  em.failover mainTask.431 - java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:308)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getSystemConnection(ConnectionService.java:683)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.getConnection(OmsServiceDriver.java:88)
	at oracle.sysman.emdrep.failover.OMSHeartbeatRecorder.getConnection(OMSHeartbeatRecorder.java:104)
	at oracle.sysman.emdrep.failover.OMSHeartbeatRecorder.heartbeat(OMSHeartbeatRecorder.java:239)
	at oracle.sysman.emdrep.failover.OMSHeartbeatRecorder.mainTask(OMSHeartbeatRecorder.java:427)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.run(OmsServiceDriver.java:164)
  </td>
</tr>
    <tr>
<td>  53  </td>
<td>  2013-11-07 02:59:08,647  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.303 - Got a fatal exeption when getting a connection; Error code = 17002; Cleaning up cache and retrying  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  54  </td>
<td>  2013-11-07 02:59:08,647  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.306 - Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:296)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getSystemConnection(ConnectionService.java:683)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.getConnection(OmsServiceDriver.java:88)
	at oracle.sysman.emdrep.jobs.Dispatcher.getConnection(Dispatcher.java:1054)
	at oracle.sysman.emdrep.jobs.Dispatcher.process(Dispatcher.java:1200)
	at oracle.sysman.emdrep.jobs.Dispatcher.mainTask(Dispatcher.java:1912)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.run(OmsServiceDriver.java:164)
  </td>
</tr>
    <tr>
<td>  55  </td>
<td>  2013-11-07 02:59:17,727  </td>
<td>  NotificationMgrThread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.303 - Got a fatal exeption when getting a connection; Error code = 17002; Cleaning up cache and retrying  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  56  </td>
<td>  2013-11-07 02:59:17,727  </td>
<td>  NotificationMgrThread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.306 - Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:296)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getSystemConnection(ConnectionService.java:683)
	at oracle.sysman.emdrep.notification.NotificationMgr.getConnection(NotificationMgr.java:252)
	at oracle.sysman.emdrep.notification.NotificationMgr.resetConnection(NotificationMgr.java:298)
	at oracle.sysman.emdrep.notification.NotificationMgr.run(NotificationMgr.java:1190)
  </td>
</tr>
    <tr>
<td>  57  </td>
<td>  2013-11-07 02:59:50,736  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.303 - Got a fatal exeption when getting a connection; Error code = 17002; Cleaning up cache and retrying  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  58  </td>
<td>  2013-11-07 02:59:50,736  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.306 - Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:296)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getPrivateConnection(ConnectionService.java:605)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getRepositoryVersionAndMode(ConnectionService.java:368)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.verifyRepositoryEx(ConnectionService.java:395)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.verifyRepository(ConnectionService.java:450)
	at oracle.sysman.emdrep.jobs.Dispatcher.mainTask(Dispatcher.java:1952)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.run(OmsServiceDriver.java:164)
  </td>
</tr>
    <tr>
<td>  59  </td>
<td>  2013-11-07 03:00:04,808  </td>
<td>  NotificationMgrThread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.303 - Got a fatal exeption when getting a connection; Error code = 17002; Cleaning up cache and retrying  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  60  </td>
<td>  2013-11-07 03:00:04,808  </td>
<td>  NotificationMgrThread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.306 - Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:296)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getSystemConnection(ConnectionService.java:683)
	at oracle.sysman.emdrep.notification.NotificationMgr.getConnection(NotificationMgr.java:252)
	at oracle.sysman.emdrep.notification.NotificationMgr.resetConnection(NotificationMgr.java:298)
	at oracle.sysman.emdrep.notification.NotificationMgr.run(NotificationMgr.java:1190)
  </td>
</tr>
    <tr>
<td>  61  </td>
<td>  2013-11-07 03:00:11,762  </td>
<td>  OmsServiceDriver thread  </td>
<td>  ERROR  </td>
<td>  conn.ConnectionService verifyRepositoryEx.433 - Invalid Connection Pool. ERROR = Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  62  </td>
<td>  2013-11-07 03:00:37,798  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.303 - Got a fatal exeption when getting a connection; Error code = 17002; Cleaning up cache and retrying  </td>
<td>    </td>
</tr>
    <tr>
<td>  63  </td>
<td>  2013-11-07 03:00:37,798  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.306 - Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:296)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getSystemConnection(ConnectionService.java:683)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.getConnection(OmsServiceDriver.java:88)
	at oracle.sysman.emdrep.failover.OMSHeartbeatRecorder.getConnection(OMSHeartbeatRecorder.java:104)
	at oracle.sysman.emdrep.failover.OMSHeartbeatRecorder.heartbeat(OMSHeartbeatRecorder.java:239)
	at oracle.sysman.emdrep.failover.OMSHeartbeatRecorder.mainTask(OMSHeartbeatRecorder.java:427)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.run(OmsServiceDriver.java:164)
  </td>
</tr>
    <tr class="alt">
<td>  64  </td>
<td>  2013-11-07 03:00:51,844  </td>
<td>  NotificationMgrThread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.303 - Got a fatal exeption when getting a connection; Error code = 17002; Cleaning up cache and retrying  </td>
<td>    </td>
</tr>
    <tr>
<td>  65  </td>
<td>  2013-11-07 03:00:51,844  </td>
<td>  NotificationMgrThread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.306 - Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:296)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getSystemConnection(ConnectionService.java:683)
	at oracle.sysman.emdrep.notification.NotificationMgr.getConnection(NotificationMgr.java:252)
	at oracle.sysman.emdrep.notification.NotificationMgr.resetConnection(NotificationMgr.java:298)
	at oracle.sysman.emdrep.notification.NotificationMgr.run(NotificationMgr.java:1190)
  </td>
</tr>
    <tr class="alt">
<td>  66  </td>
<td>  2013-11-07 03:00:58,833  </td>
<td>  OmsServiceDriver thread  </td>
<td>  ERROR  </td>
<td>  em.failover mainTask.431 - java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:308)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getSystemConnection(ConnectionService.java:683)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.getConnection(OmsServiceDriver.java:88)
	at oracle.sysman.emdrep.failover.OMSHeartbeatRecorder.getConnection(OMSHeartbeatRecorder.java:104)
	at oracle.sysman.emdrep.failover.OMSHeartbeatRecorder.heartbeat(OMSHeartbeatRecorder.java:239)
	at oracle.sysman.emdrep.failover.OMSHeartbeatRecorder.mainTask(OMSHeartbeatRecorder.java:427)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.run(OmsServiceDriver.java:164)
  </td>
</tr>
    <tr>
<td>  67  </td>
<td>  2013-11-07 03:01:19,847  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.303 - Got a fatal exeption when getting a connection; Error code = 17002; Cleaning up cache and retrying  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  68  </td>
<td>  2013-11-07 03:01:19,847  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.306 - Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:296)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getSystemConnection(ConnectionService.java:683)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.getConnection(OmsServiceDriver.java:88)
	at oracle.sysman.emdrep.jobs.Dispatcher.getConnection(Dispatcher.java:1054)
	at oracle.sysman.emdrep.jobs.Dispatcher.process(Dispatcher.java:1200)
	at oracle.sysman.emdrep.jobs.Dispatcher.mainTask(Dispatcher.java:1912)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.run(OmsServiceDriver.java:164)
  </td>
</tr>
    <tr>
<td>  69  </td>
<td>  2013-11-07 03:01:38,880  </td>
<td>  NotificationMgrThread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.303 - Got a fatal exeption when getting a connection; Error code = 17002; Cleaning up cache and retrying  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  70  </td>
<td>  2013-11-07 03:01:38,880  </td>
<td>  NotificationMgrThread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.306 - Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:296)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getSystemConnection(ConnectionService.java:683)
	at oracle.sysman.emdrep.notification.NotificationMgr.getConnection(NotificationMgr.java:252)
	at oracle.sysman.emdrep.notification.NotificationMgr.resetConnection(NotificationMgr.java:298)
	at oracle.sysman.emdrep.notification.NotificationMgr.run(NotificationMgr.java:1190)
  </td>
</tr>
    <tr>
<td>  71  </td>
<td>  2013-11-07 03:02:01,891  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.303 - Got a fatal exeption when getting a connection; Error code = 17002; Cleaning up cache and retrying  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  72  </td>
<td>  2013-11-07 03:02:01,891  </td>
<td>  OmsServiceDriver thread  </td>
<td>  WARN  </td>
<td>  jdbc.ConnectionCache _getConnection.306 - Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>  java.sql.SQLException: Io “Ï≥£: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:254)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:386)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:493)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:164)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:34)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:324)
	at oracle.jdbc.pool.OracleConnectionPoolDataSource.getPooledConnection(OracleConnectionPoolDataSource.java:114)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getNewPoolOrXAConnection(OracleConnectionCacheImpl.java:694)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getPooledConnection(OracleConnectionCacheImpl.java:540)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:346)
	at oracle.jdbc.pool.OracleConnectionCacheImpl.getConnection(OracleConnectionCacheImpl.java:324)
	at oracle.sysman.util.jdbc.ConnectionCache._getConnection(ConnectionCache.java:296)
	at oracle.sysman.util.jdbc.ConnectionCache.getUnwrappedConnection(ConnectionCache.java:423)
	at oracle.sysman.emSDK.svc.conn.FGAConnectionCache.getFGAConnection(FGAConnectionCache.java:156)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getPrivateConnection(ConnectionService.java:605)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.getRepositoryVersionAndMode(ConnectionService.java:368)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.verifyRepositoryEx(ConnectionService.java:395)
	at oracle.sysman.emSDK.svc.conn.ConnectionService.verifyRepository(ConnectionService.java:450)
	at oracle.sysman.emdrep.jobs.Dispatcher.mainTask(Dispatcher.java:1952)
	at oracle.sysman.emdrep.omsservice.OmsServiceDriver.run(OmsServiceDriver.java:164)
  </td>
</tr>
    <tr>
<td>  73  </td>
<td>  2013-11-07 03:02:21,213  </td>
<td>  XMLLoader0  </td>
<td>  ERROR  </td>
<td>  emdrep.XMLLoaderContext logLoaderParameters.2179 - πÿ±’µƒ¡¨Ω”  </td>
<td>  java.sql.SQLException: πÿ±’µƒ¡¨Ω”
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:111)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:145)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:207)
	at oracle.jdbc.driver.PhysicalConnection.createStatement(PhysicalConnection.java:912)
	at oracle.jdbc.driver.PhysicalConnection.createStatement(PhysicalConnection.java:888)
	at oracle.jdbc.driver.PhysicalConnection.initUserName(PhysicalConnection.java:3108)
	at oracle.jdbc.driver.PhysicalConnection.getUserName(PhysicalConnection.java:3128)
	at oracle.jdbc.OracleConnectionWrapper.getUserName(OracleConnectionWrapper.java:321)
	at oracle.sysman.util.jdbc.ConnectionWrapper.getUserName(ConnectionWrapper.java:1143)
	at oracle.sql.SQLName.init(SQLName.java:141)
	at oracle.sql.SQLName.<init>(SQLName.java:89)
	at oracle.sql.ArrayDescriptor.createDescriptor(ArrayDescriptor.java:148)
	at oracle.sql.ArrayDescriptor.createDescriptor(ArrayDescriptor.java:114)
	at oracle.sysman.emdrep.dbjava.loader.XMLLoaderContext.logLoaderParameters(XMLLoaderContext.java:2157)
	at oracle.sysman.emdrep.dbjava.loader.XMLLoaderContext.keepAlive(XMLLoaderContext.java:572)
	at oracle.sysman.emdrep.dbjava.loader.XMLLoader.run(XMLLoader.java:1140)
	at java.lang.Thread.run(Thread.java:534)
  </td>
</tr>
    <tr class="alt">
<td>  74  </td>
<td>  2013-11-07 03:02:22,898  </td>
<td>  OmsServiceDriver thread  </td>
<td>  ERROR  </td>
<td>  conn.ConnectionService verifyRepositoryEx.433 - Invalid Connection Pool. ERROR = Io “Ï≥£: The Network Adapter could not establish the connection  </td>
<td>    </td>
</tr>
    <tr>
<td>  75  </td>
<td>  2013-11-07 03:02:22,898  </td>
<td>  OmsServiceDriver thread  </td>
<td>  ERROR  </td>
<td>  em.jobs die.1129 - Dispatcher: causing a restart  </td>
<td>    </td>
</tr>
    <tr class="alt">
<td>  76  </td>
<td>  2013-11-07 03:02:22,898  </td>
<td>  OmsServiceDriver thread  </td>
<td>  ERROR  </td>
<td>  emd.main restart.389 - HealthMonitor 2013-11-7 3:02:22 Job Dispatcher error: Could not get connection  </td>
<td>  
  </td>
</tr>
  </table>  <br/>
<footer align="center">&copy;2014-2017 CORSWORK</footer></body>
</html>